[package]
name = "wali"
version = "0.1.1"
description = "Wali — unofficial Linux WhatsApp client"
license = "MIT"
edition = "2021"

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
semver = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tauri = { version = "2", features = ["tray-icon"] }
tauri-plugin-single-instance = "2"
ureq = "2"

[target.'cfg(target_os = "linux")'.dependencies]
gtk = "0.18"
webkit2gtk = { version = "=2.0", features = ["v2_40"] }
notify-rust = "4"

[profile.release]
strip = true
